#!/bin/bash
loader_opts=${1:-all}
folder=$(pwd)/migra
test -d $folder || mkdir $folder
echo "zp-schema --console"
zp-schema --console
echo "zp-extract --console all --output-dir $folder"
zp-extract --console all --output-dir $folder
echo "zp-loader --console --quiet  ${loader_opts} --input-dir $folder"
zp-loader --console --quiet ${loader_opts} --input-dir $folder 
