#!/bin/bash


# Fixes all little inconsistent data
# This script is meant to be executed once, with all the inconsistencies.
# and changes to be made in the source production database before the migration process.
#
# We monitor the changes with SELECT name,session,comment FROM summary_t WHERE comment IS NOT NULL ORDER BY session, name;


if test -f .env; then
	source .env
else
	echo "No environemnt variables file found. Exiting"
	exit 255
fi

DATABASE=${1:-${SOURCE_DATABASE}}

echo "Applying database fixes before migration."
sqlite3 ${DATABASE} <<EOF
.echo on
BEGIN;

--------------------------------------------------
-- Fix 20.44 => 20.50 as ficticious ZP in rounds_t
--------------------------------------------------

UPDATE rounds_t SET zp_fict = 20.50
WHERE zp_fict = 20.44;

--------------------------
-- Fix collector weirdness
--------------------------

UPDATE summary_t SET collector = 'standard'
WHERE collector LIKE 'Sí%' OR collector LIKE 'Si%';

-------------------------------------------------------
-- Fix a bunch of comment updates with the same pattern
-------------------------------------------------------

UPDATE summary_t SET collector = 'standard'
WHERE collector LIKE 'Sí%' OR collector LIKE 'Si%';

UPDATE summary_t SET comment = 'Phot: ' || comment
WHERE comment IS NOT NULL AND comment NOT LIKE 'Phot:%' -- makes it retryable
AND comment LIKE 'Updated with tessdb MAC%'

UPDATE summary_t SET comment = 'Phot: ' || comment
WHERE comment IS NOT NULL AND comment NOT LIKE 'Phot:%' -- makes it retryable
AND comment LIKE 'MAC de tessdb%'

--------------------------------------------------------------
-- Fix individual photometers to add Photometer level comments
--------------------------------------------------------------

UPDATE summary_t SET comment = 'Phot: ' || comment
WHERE comment NOT LIKE 'Phot:%' -- makes it retryable
AND name = 'stars3' AND session = '1000-01-01T00:00:00'

UPDATE summary_t SET comment = 'Phot: ' || comment
WHERE comment NOT LIKE 'Phot:%' -- makes it retryable
AND name = 'stars8' AND session = '1000-01-01T00:07:00'

UPDATE summary_t SET comment = 'Phot: ' || comment
WHERE comment NOT LIKE 'Phot:%' -- makes it retryable
AND name = 'stars15' AND session = '1000-01-01T00:14:00'

UPDATE summary_t SET comment = 'Phot: ' || comment
WHERE comment NOT LIKE 'Phot:%' -- makes it retryable
AND name = 'stars17' AND session = '1000-01-01T00:16:00'


-----------------------------------------------------------
-- Fix individual photometers to add Summary level comments
-----------------------------------------------------------




COMMIT;

EOF